import sys
linux = sys.platform == 'linux2'

env = Environment()

if linux:
	env['CC'] = 'clang'
	env['CXX'] = 'clang++'
	env.ParseConfig('pkg-config --cflags --libs lua5.1-c++')
else:
	env.Tool('mingw')

env['CPPPATH'] = '../../..'

env.Object('../luatools.cpp', CPPFLAGS='-std=c++11')

env.Program('lvm', ['lvm.cpp', '../luatools.o'], CPPFLAGS='-std=c++11')
env.Program('lvm98', ['lvm98.cpp', '../luatools.o'], CPPFLAGS='-std=c++98')
	
